In [2]:
import numpy as np

In [16]:
# vectorization.......
arr=np.array([1,2,3])
print(arr*2)  
print(arr+5)

#boadcastingg.......

print(arr+[20])
print(arr+[[1,2,3],[4,5,6]])


[2 4 6]
[6 7 8]
[21 22 23]
[[2 4 6]
 [5 7 9]]
