In [1]:
import numpy as np

In [6]:
# Aggregation.....
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

15
120
5
1
3.0
3.0
1.4142135623730951
2.0
0
4


In [11]:
# Power

arr=np.array([1,2,3,4])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))
print(np.pow(2,4))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 1  8 27 64]
16


In [18]:
# Rounding
a=3.4455
print(np.round(3.14))
print(np.round(arr))
print(np.round(a))
print(np.ceil(a))
print(np.floor(a))
print(np.trunc(a))

3.0
[1 2 3 4]
3.0
4.0
3.0
3.0


In [25]:
# Log and Expontential
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

[0.         0.69314718 1.09861229 1.38629436]
[0.         0.30103    0.47712125 0.60205999]
[0.        1.        1.5849625 2.       ]


In [30]:
# Extra....
print(np.unique(arr))
print(np.unique([2,2,2,23,3,3,4]))
print(np.sort(arr))
print(np.abs(arr))
print(np.abs(-12))

[1 2 3 4]
[ 2  3  4 23]
[1 2 3 4]
[1 2 3 4]
12
