# Creating NumPy Array and their properties...................

In [3]:
import numpy as np

In [4]:
# Create - from lists
arr= np.array([1,3,5,6,7,0])
print(arr,type(arr))
print(arr.dtype)
print(arr.shape)

arr2=np.array([1,2,3,4,5,6,7,"numbers"])
print(arr2, type(arr2))
print(arr2.dtype)
print(arr2.shape)


[1 3 5 6 7 0] <class 'numpy.ndarray'>
int64
(6,)
['1' '2' '3' '4' '5' '6' '7' 'numbers'] <class 'numpy.ndarray'>
<U21
(8,)


In [5]:
# Creating 2-D array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,type(arr2D),arr2D.dtype,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [6]:
#creating a array of any dimention with zeros
arr3=np.zeros((3,3),dtype="int64")  # prefill
print(arr3,arr3.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)


In [7]:
arr3=np.ones((5, )) #prefill
print(arr3,arr3.shape)

[1. 1. 1. 1. 1.] (5,)


In [8]:
arr3=np.full((3,4), 100) # prefill with value
print(arr3,arr3.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


In [12]:
arr3=np.eye(3) #identity matrix
print(arr3,arr3.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)


In [10]:
# np.arr(start,end,step) -> range elements
arr3=np.arange(0,11,2)
print(arr3,arr3.shape)


[ 0  2  4  6  8 10] (6,)


In [11]:
# evenly spaced arrays
arr6=np.linspace(1,100,4)
print(arr6,arr6.shape)

[  1.  34.  67. 100.] (4,)
