In [1]:
import numpy as np

# Properties of NumPy Array

In [10]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1.shape)
print(arr1.size)    #Total elements -->n*m
print(arr1.dtype)
print(arr1.ndim)

(3, 3)
9
int64
2


In [8]:
arr=np.array([3,4,5])
print(arr.size)

3


In [11]:
float_arr=arr1.astype(np.float64)
print(float_arr, float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [12]:
# Reshaping array
arr=np.array([[1,2,3,4,5,6],[7,8,9,0,1,2]])
arr1=arr.reshape(3,4)
print(arr1)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]


In [15]:
# Flattened....(converting into 1-D array)
arr=np.array([[1,2,3,4,5,6],[7,8,9,0,1,2]])
arr1=arr.flatten()
print(arr1)
print(arr1.shape)


[1 2 3 4 5 6 7 8 9 0 1 2]
(12,)


In [16]:
#Indexing in 1-D array....
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[5])

1
6


In [18]:
#Indexing in 2-D array ....
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0][2])
print(arr[2][2])
print(arr[2][0])

3
9
7


In [23]:
#fancy indexing....(only for 1-D array........
arr=np.array([1,2,3,4,5,6,7,8,9])
idx=[1,2,4]
print(arr[idx])

[2 3 5]


In [27]:
# Boolean Indexing ....
print(arr>3) #[False False False  True  True  True  True  True  True]
print(arr[arr>3]) # [4 5 6 7 8 9]
print(arr[arr%2==0])  #[2 4 6 8]
print(arr % 2==0)     #[False  True False  True False  True False  True False]

[False False False  True  True  True  True  True  True]
[4 5 6 7 8 9]
[2 4 6 8]
[False  True False  True False  True False  True False]


In [33]:
# slicing..
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])

[2 3 4]


In [36]:
#for checking time taken by list in slicing and in numpy arrray
import sys
import time 

In [40]:
# this is for showing time taken during slicing in array is lesser than list
# for py_list......

py_list = [1,2,3,4,5,6]
start=time.time()
py_slice=py_list[1:4]
end=time.time()
print(f"time taken by the py_list during slicing is: {end-start}")

#for np_arrray....
np_array=np.array(py_list)
start=time.time()
np_slice=np_array[1:4]
end=time.time()
print(f"time taken by the np_array during slicing is: {end-start}")

time taken by the py_list during slicing is: 0.00012755393981933594
time taken by the np_array during slicing is: 0.0002193450927734375


In [46]:
# this is for showing that in list during a new copy is created 
#and in array no copy is created

pylist=[1,2,3,4,5,6,7,8]
pyslice=pylist[1:4]
pyslice[0]=20
print(pyslice)
print(pylist)  # changes do not reflect in the original list

np_array=np.array([1,2,3,4,5,6,7,8])
np_slicing=np_array[1:4]  # if creating copy is needed they we use .copy()
np_slicing[0]=20
print(np_slicing)
print(np_array)  # change do reflect in the original array

[20, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]
[20  3  4]
[ 1 20  3  4  5  6  7  8]


In [51]:
# concept of copying an array 

# if copied then the value changed will not reflect in the previouse array
np_array=np.array([1,2,3,4,5,6,7,8])
arr=np_array.copy()
arr[1]=0
print(arr)
print(np_array)
# if not copied they it will reflect i nthe previous array also 
arr=np_array
arr[0]=0
print(np_array)
print(arr)

[1 0 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[0 2 3 4 5 6 7 8]
[0 2 3 4 5 6 7 8]
