# Multi-Dimensional arrays

In [2]:
import numpy as np

In [3]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9,]])
print(arr2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#sum of all elements of the matrix
print(arr2D.sum())
# OR
print(np.sum(arr2D))

45
45


In [14]:
#sum of columns of the matrix
print(np.sum(arr2D,axis=0))
print(arr2D.sum(axis=0))

[12 15 18]
[12 15 18]


In [15]:
#sum of rows of the matrix
print(np.sum(arr2D,axis=1))
print(arr2D.sum(axis=1))

[ 6 15 24]
[ 6 15 24]


In [16]:
#slicing in 2D array
print(arr2D[0:1,0:3])

[[1 2 3]]
