In [45]:
import numpy as np

In [51]:
# 3-D Array (access and creating)
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr3D,arr3D.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] (3, 3, 3)


In [53]:
#indexing in 3-D array
print(arr3D[1,1,2]) # 15

15


In [56]:
#slicing in 3-D array

#taking out first row of all the layers
print(arr3D[:,0:1,:])

#taking out first columns of all the layers
print(arr3D[:,:,0:1])

[[[ 1  2  3]]

 [[10 11 12]]

 [[19 20 21]]]
[[[ 1]
  [ 4]
  [ 7]]

 [[10]
  [13]
  [16]]

 [[19]
  [22]
  [25]]]
